---

- name: Add Ceph repo keyring
  apt_key:
    url: "{{ ceph_repo_sig }}"

- name: Add Ceph repo
  apt_repository:
    repo: "deb https://download.ceph.com/debian-luminous/ {{ ansible_distribution_release }} main"

- name: Install base software set
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ ceph_packages }}"