---

- name: Install FreeIPA client packages
  apt:
    name: freeipa-client
    state: present

- name: Check if IPA joined
  stat:
    path: /etc/ipa/default.conf
  register: stat_result
  changed_when: False

- name: Join FreeIPA
  shell: ipa-client-install --hostname="{{ inventory_hostname }}" --domain=sanbi.ac.za --server=freeipa.sanbi.ac.za --realm=SANBI.AC.ZA -p admin --password="{{ var_freeipa_pass }}" --force-join --unattended
  when: stat_result.stat.exists == False
