---

- name: Install FreeIPA client packages
  apt:
    name: freeipa-client
    state: present
    autoclean: yes
  changed_when: false

- name: Check if IPA joined
  stat:
    path: /etc/ipa/default.conf
  register: stat_result
  changed_when: False

- name: Join FreeIPA
  shell: ipa-client-install --hostname="{{ inventory_hostname }}" --domain="{{ freeipa_domain }}" --server="{{ freeipa_server_hostname }}" --realm="{{ freeipa_realm }}" -p "{{ freeipa_user }}" --password="{{ freeipa_pass }}" --unattended
  when: stat_result.stat.exists == False

- name: Forcefully rejoin FreeIPA
  block:
    - name: Remove FreeIPA
      shell: ipa-client-install --uninstall --force --quiet --unattended
      ignore_errors: yes

    - name: Rejoin FreeIPA
      shell: ipa-client-install --hostname="{{ inventory_hostname }}" --domain="{{ freeipa_domain }}" --server="{{ freeipa_server_hostname }}" --realm="{{ freeipa_realm }}" -p "{{ freeipa_user }}" --password="{{ freeipa_pass }}" --force-join -f --unattended
  when: (stat_result.stat.exists == True) and (freeipa_force_join == True)