---

- name: Install node-exporter
  block:

    - name: Download node-exporter {{ node_exporter_version }} binary
      tags:
        - download
      local_action:
        module: unarchive
        src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp/
        remote_src: yes
      run_once: True

    - name: Distribute node-exporter
      tags:
        - download
      copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: /opt/node_exporter
        owner: monitor
        mode: u=rwx,g=rx,o=rx

    - name: Assert that var 'consul_server_addr' is set
      assert:
        that:
          - "consul_server_addr != ''"
        fail_msg: "'consul_server_addr' must be set to a valid server address"

    - name: Create service files
      template:
        src: "{{ role_path }}/files/node_exporter.service.j2"
        dest: /etc/systemd/system/node_exporter.service
      notify:
        - Systemd restart node_exporter
        
  when: not ( (enable_node_exporter is not defined) or (not enable_node_exporter) )

- name: Install Consul
  block:

    - name: Download Consul {{ consul_version }} binary
      tags:
        - download
      local_action:
        module: unarchive
        src: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
        dest: /tmp/
        remote_src: yes
      run_once: True
 
    - name: Distribute consul
      tags:
        - download
      copy:
        src: "/tmp/consul"
        dest: /opt/consul

    - name: Create consul directory
      file:
        path: /opt/consul.d/
        state: directory
 
    - name: Template out consul data
      template:
        src: "{{ role_path }}/files/services.json.j2"
        dest: /opt/consul.d/services.json
    
    - name: Ensure consul binary executable
      file:
        dest: /opt/consul
        mode: a+x
    
    - name: Create service files
      template:
        src: "{{ role_path }}/files/consul.service.j2"
        dest: /etc/systemd/system/consul.service
      notify:
        - Systemd restart consul

  when: not ( (enable_consul is not defined) or (not enable_consul) )
