---

- name: Install node-exporter
  block:

    - name: Ensure node-exporter directory exists
      file:
        path: /opt/node_exporter
        state: directory
        owner: monitor
 
    - name: Download latest node-exporter binary
      unarchive:
        src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        remote_src: yes
        dest: /opt/node_exporter
        owner: monitor
    - name: Install Consul
      unarchive:
        src: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
        dest: /opt/
        remote_src: yes

 
    - name: Create service file
      template:
        src: "{{ role_path }}/files/node_exporter.service.j2"
        dest: /etc/systemd/system/node_exporter.service
 
    - name: Reload services
      systemd:
        name: node_exporter.service
        daemon_reload: yes
        enabled: yes
        state: started
 
    - name: Create consul directory
      file:
        path: /opt/consul.d/
        state: directory
 
    - name: Template out consul data
      template:
        src: "{{ role_path }}/files/services.json.j2"
        dest: /opt/consul.d/services.json
  
  when: not ( (enable_node_exporter is not defined) or (not enable_node_exporter) )