---

- name: Install node-exporter
  block:
    - name: Download latest node-exporter binary
      tags:
        - download
      local_action:
        module: unarchive
        src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp/
        remote_src: yes
      run_once: True

    - name: Distribute node-exporter
      tags:
        - download
      copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: /opt/node_exporter
        owner: monitor
        mode: u=rwx,g=rx,o=rx

    - name: Create service files
      template:
        src: "{{ role_path }}/files/node_exporter.service.j2"
        dest: /etc/systemd/system/node_exporter.service

    - name: Reload services
      systemd:
        name: "node_exporter.service"
        daemon_reload: yes
        enabled: yes
        state: started
  
  when: not ( (enable_node_exporter is not defined) or (not enable_node_exporter) )